### ISSUE TITLE
add rule for 300__a

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#184] opened 2019-01-22 12:59 UTC
Add rule: 300__a when the value is not fully numeric, the value should go in the entity: public_notes with, if possible, the string "Physical description:" in front.
-> This information will be needed for the migration (mostly for the volumes), and might be deleted afterwards, since this information should be retrievable in different ways with the new structuration of data.

**Comment by kprzerwa** [comment] 2019-01-22 16:21
@agentilb the rule for 300__a already exists and it won't be ever fully numeric because it describes number of pages, by using the format '30 p'). Did you mean 300__b?

**Comment by agentilb** [comment] 2019-01-23 08:59
Indeed, for the time being the rule works well, in case we have only page numbers. 
The problem is when we have something else: then the script doesn't know what to do with this information. 
Maybe I'll first check all the possible values there, and then I'll identify a more precise rule. Would you be able to send me a list of values in 300__a that are not "xx p"?
Thanks!

**Comment by agentilb** [comment] 2019-01-24 11:40
Indeed, there is in this field other information than page numbers that is why we need either to clean them or to find a different rule for this information if it needs to be kept. I finally found a way to have an almost complete overview of those values, and I'll come back to you with a more precise rule.

**Comment by agentilb** [comment] 2019-01-28 16:59
So, we will create another entity for the information in 300 that is not a pagination information. 
the entity is the following: 
----
object_description:
    description: ':MARC: ``300`` when no pagination'
    title: Addition information about the physical description of an object
    type: string
----
Could you please add it to the model?
The rule is: any value in 300 that doesn't fit in the number_of_pages entity goes there. 

We have noted that many of those information need to be cleaned. 
It will be done before the migration, so we migrate only what is relevant.

**Comment by kprzerwa** [comment] 2019-01-29 08:20
@agentilb what about the cases when the field contains values like 'multip. p' ? It is a pagination information, but not really worthy, as it does not have any number.

**Comment by topless** [comment] 2019-01-31 12:45
Hello again @agentilb, I followed the conversation with @kprzerwa and I want to propose my solution with what I understood. Whenever we encounter a `300` field, we will try to extract the number if any and assign it to `number_of_pages`. All rest information (even if we don't find a number) can go in `physical_description` field which I will introduce. 

Later we can decide what to do with this information, but like this won't require any manual work on your behalf.

I might be missing something obvious so please feel free to provide any guidance.

**Comment by agentilb** [comment] 2019-01-31 14:54
That is perfect: take everything that is "n p" 'is number_of_pages' and the rest in 'physical_description'. 
Ignore when the value is "mult. p", because we know already we do not need it anymore.

**Comment by ludmilamarian** [comment] 2019-02-06 10:46
Overview of all the possible values stored in `300__a`:

* 4'682 different values present: [300_a_all.txt](https://github.com/CERNDocumentServer/cds-dojson/files/2835953/300_a_all.txt)
* 791 values do not match `'^[0-9]+\s*p'`: [300_a_nonstandard.txt](https://github.com/CERNDocumentServer/cds-dojson/files/2835954/300_a_nonstandard.txt)

**Comment by agentilb** [comment] 2019-02-07 10:08
@ludmilamarian many values here: 300_a_all.txt need to be cleaned before the migration.

**Closed** 2019-02-11 14:24 UTC
Labels: dojson, migration, review
